# Export the print layout to PDF.
#
# Run this from the QGIS Python console (Plugins → Python Console):
#
#   exec(open("~/work/alidade/alidade/util/export_pdf.py").read())
#
# Requirements:
#   - A QGIS project must be open (output/project.qgs).
#   - output/print.qpt must exist alongside it (generated by make build).
#
# The script loads the QPT template if it is not already in the Layout Manager,
# exports to output/print.pdf, and prints the path on success.

from pathlib import Path

from qgis.core import QgsLayoutExporter, QgsPrintLayout, QgsProject, QgsReadWriteContext
from qgis.PyQt.QtXml import QDomDocument

_LAYOUT_NAME = "print"

_project = QgsProject.instance()
_output_dir = Path(_project.fileName()).parent

layout = _project.layoutManager().layoutByName(_LAYOUT_NAME)

if layout is None:
    qpt_path = _output_dir / "print.qpt"
    if not qpt_path.exists():
        print(f"Template not found: {qpt_path} — run 'make build' first")
    else:
        doc = QDomDocument()
        doc.setContent(qpt_path.read_text())
        layout = QgsPrintLayout(_project)
        layout.readXml(doc.documentElement(), doc, QgsReadWriteContext())
        layout.setName(_LAYOUT_NAME)
        _project.layoutManager().addLayout(layout)

if layout is not None:
    pdf_path = str(_output_dir / "print.pdf")
    result = QgsLayoutExporter(layout).exportToPdf(
        pdf_path, QgsLayoutExporter.PdfExportSettings()
    )
    if result == QgsLayoutExporter.Success:
        print(f"Exported: {pdf_path}")
    else:
        print(f"Export failed (QgsLayoutExporter result code: {result})")
