# Export the print layout to PDF.
#
# Run this from the QGIS Python console (Plugins → Python Console):
#
#   exec(open("~/work/alidade/alidade/util/export_pdf.py").read())
#
# Optional variable to set before exec:
#
#   print_prefix = "overview"   # loads overview.qpt, writes overview.pdf
#                               # default: "print"
#
# Requirements:
#   - A QGIS project must be open (output/project.qgs).
#   - output/<prefix>.qpt must exist alongside it (generated by make build).
#
# The script loads the QPT template if it is not already in the Layout Manager,
# exports to output/<prefix>.pdf, and prints the path on success.

from pathlib import Path

from qgis.core import QgsLayoutExporter, QgsPrintLayout, QgsProject, QgsReadWriteContext
from qgis.PyQt.QtXml import QDomDocument


def _print_pdf(filename: str = "print.pdf") -> None:
    if not layout:
        return
    pdf_path = str(_output_dir / filename)
    result = QgsLayoutExporter(layout).exportToPdf(
        pdf_path, QgsLayoutExporter.PdfExportSettings()
    )
    if result == QgsLayoutExporter.Success:
        print(f"Exported: {pdf_path}")
    else:
        print(f"Export failed (QgsLayoutExporter result code: {result})")


def _load_layout(layout_name, qpt_filename: str = "print.qpt") -> None:
    qpt_path = _output_dir / qpt_filename
    if not qpt_path.exists():
        print(f"Template not found: {qpt_path} — run 'make build' first")
    else:
        doc = QDomDocument()
        doc.setContent(qpt_path.read_text())
        layout = QgsPrintLayout(_project)
        layout.readXml(doc.documentElement(), doc, QgsReadWriteContext())
        layout.setName(layout_name)
        _project.layoutManager().addLayout(layout)


_project = QgsProject.instance()
_output_dir = Path(_project.fileName()).parent

_prefix = globals().get("print_prefix", "print")

layout = _project.layoutManager().layoutByName(_prefix)

if layout is None:
    _load_layout(_prefix, f"{_prefix}.qpt")

_print_pdf(f"{_prefix}.pdf")
