"""Generate a per-project GEN.mk from the layer graph."""

import argparse
import re
from graphlib import TopologicalSorter
from pathlib import Path

from alidade.models import BoundProject, Layer
from alidade.util.helpers import bind_project


def _topo_sort(spec: BoundProject) -> list[Layer]:
    """Return layers-with-actions in dependency order."""
    steps = {layer.id: layer for layer in spec.layers if layer.action}
    ts = TopologicalSorter(
        {
            layer.id: [inp.id for inp in layer.inputs]
            for layer in spec.layers
            if layer.action
        }
    )
    return [steps[layer_id] for layer_id in ts.static_order() if layer_id in steps]


# TODO: replace regex operations on layer fields with Layer objects
# Matches id="..." in layer source files to map layer IDs to their defining file.
LAYER_ID_PATTERN = re.compile(r'id="([^"]+)"')


def _build_source_index(layers_dir: Path) -> dict[str, Path]:
    """Build {layer_id: source_file} by reading each layers/*.py file once."""
    index: dict[str, Path] = {}
    for f in sorted(layers_dir.glob("*.py")):
        for m in LAYER_ID_PATTERN.finditer(f.read_text()):
            index.setdefault(m.group(1), f)
    return index


def generate(spec: BoundProject) -> str:
    """Return Makefile text expressing the layer dependency graph."""
    project_path = spec.project_path
    output_path = spec.output_path
    layers_dir = project_path / "layers"
    util_py = project_path / "util.py"

    lines: list[str] = [
        "# Auto-generated by `alidade-makefile` — do not edit.",
        "",
        f"OUTPUT := {output_path}",
        f"PROJECT := {project_path}",
        "",
    ]

    formatted_stamp = str(output_path / ".formatted")
    fmt_sources = [str(project_path / "project.py")]
    if layers_dir.exists():
        fmt_sources.extend(str(f) for f in sorted(layers_dir.glob("*.py")))
    fmt_prereqs = " \\\n        ".join(fmt_sources)
    fmt_cmd = f"uv run black {project_path / 'project.py'}"
    if layers_dir.exists():
        fmt_cmd += f" {layers_dir}"
    lines.append(f"{formatted_stamp}: {fmt_prereqs}")
    lines.append(f"\t{fmt_cmd}")
    lines.append("\ttouch $@")
    lines.append("")

    ordered = _topo_sort(spec)
    source_index = _build_source_index(layers_dir) if layers_dir.exists() else {}
    all_outputs: list[str] = []

    for layer in ordered:
        bound = layer.bind(project_path, with_inputs=True)
        output = bound.path
        all_outputs.append(str(output))

        prereqs: list[str] = [formatted_stamp]
        src = source_index.get(layer.id)
        if src is not None:
            prereqs.append(str(src))
        if util_py.exists():
            prereqs.append(str(util_py))
        for inp in layer.inputs:
            prereqs.append(str(inp.bind(project_path).path))
        if layer.raw_file is not None:
            prereqs.append(str((project_path / layer.raw_file).resolve()))

        prereq_str = " \\\n        ".join(prereqs)
        lines.append(f"{output}: {prereq_str}")
        lines.append(f"\tuv run alidade-build-layer {project_path} {layer.id}")
        lines.append("")

    lines.append(".PHONY: all")
    if all_outputs:
        lines.append(f"all: {' '.join(all_outputs)}")
    else:
        lines.append("all:")
    lines.append("")

    return "\n".join(lines)


def write(spec: BoundProject) -> Path:
    """Write GEN.mk to spec.output_path and return the path."""
    spec.output_path.mkdir(parents=True, exist_ok=True)
    path = spec.output_path / "GEN.mk"
    path.write_text(generate(spec))
    return path


def main() -> None:
    """Generate output/GEN.mk from project.py."""
    parser = argparse.ArgumentParser(
        description="Generate output/GEN.mk from project.py."
    )
    parser.add_argument("project_dir", help="Path to project directory")
    args = parser.parse_args()
    project_path = (Path.cwd() / args.project_dir).resolve()
    spec = bind_project(project_path)
    path = write(spec)
    print(path)
