"""Generate a per-project GEN.mk from the layer graph."""

import argparse
from pathlib import Path

from alidade.models import BoundProject, Layer
from alidade.util.helpers import bind_project


def _visit(
    layer_id: str,
    steps: dict[str, Layer],
    visited: set[str],
    ordered: list[Layer],
) -> None:
    """Add layer_id and its unvisited dependencies to ordered in topological order."""
    if layer_id in visited:
        return
    visited.add(layer_id)
    layer = steps.get(layer_id)
    if layer is None:
        return
    assert layer.action is not None
    for inp in layer.inputs:
        _visit(inp.id, steps, visited, ordered)
    ordered.append(layer)


def _topo_sort(spec: BoundProject) -> list[Layer]:
    """Return layers-with-actions in dependency order."""
    steps = {layer.id: layer for layer in spec.layers if layer.action}
    ordered: list[Layer] = []
    visited: set[str] = set()
    for layer in spec.layers:
        if layer.action is not None:
            _visit(layer.id, steps, visited, ordered)
    return ordered


def _find_layer_source(layer_id: str, layers_dir: Path) -> Path | None:
    """Find the layers/*.py file that defines layer_id."""
    needle = f'id="{layer_id}"'
    for f in sorted(layers_dir.glob("*.py")):
        if needle in f.read_text():
            return f
    return None


def generate(spec: BoundProject) -> str:
    """Return Makefile text expressing the layer dependency graph."""
    project_path = spec.project_path
    output_path = spec.output_path
    layers_dir = project_path / "layers"
    util_py = project_path / "util.py"

    lines: list[str] = [
        "# Auto-generated by `alidade-makefile` — do not edit.",
        "",
        f"OUTPUT := {output_path}",
        f"PROJECT := {project_path}",
        "",
    ]

    formatted_stamp = str(output_path / ".formatted")
    fmt_sources = [str(project_path / "project.py")]
    if layers_dir.exists():
        fmt_sources.extend(str(f) for f in sorted(layers_dir.glob("*.py")))
    fmt_prereqs = " \\\n        ".join(fmt_sources)
    fmt_cmd = f"uv run black {project_path / 'project.py'}"
    if layers_dir.exists():
        fmt_cmd += f" {layers_dir}"
    lines.append(f"{formatted_stamp}: {fmt_prereqs}")
    lines.append(f"\t{fmt_cmd}")
    lines.append("\ttouch $@")
    lines.append("")

    ordered = _topo_sort(spec)
    all_outputs: list[str] = []

    for layer in ordered:
        bound = layer.bind(project_path, with_inputs=True)
        output = bound.path
        all_outputs.append(str(output))

        prereqs: list[str] = [formatted_stamp]
        src = _find_layer_source(layer.id, layers_dir)
        if src is not None:
            prereqs.append(str(src))
        if util_py.exists():
            prereqs.append(str(util_py))
        for inp in layer.inputs:
            prereqs.append(str(inp.bind(project_path).path))
        if layer.raw_file is not None:
            prereqs.append(str((project_path / layer.raw_file).resolve()))

        prereq_str = " \\\n        ".join(prereqs)
        lines.append(f"{output}: {prereq_str}")
        lines.append(f"\tuv run alidade-build-layer {project_path} {layer.id}")
        lines.append("")

    lines.append(".PHONY: all")
    if all_outputs:
        lines.append(f"all: {' '.join(all_outputs)}")
    else:
        lines.append("all:")
    lines.append("")

    return "\n".join(lines)


def write(spec: BoundProject) -> Path:
    """Write GEN.mk to spec.output_path and return the path."""
    spec.output_path.mkdir(parents=True, exist_ok=True)
    path = spec.output_path / "GEN.mk"
    path.write_text(generate(spec))
    return path


def main() -> None:
    """Generate output/GEN.mk from project.py."""
    parser = argparse.ArgumentParser(
        description="Generate output/GEN.mk from project.py."
    )
    parser.add_argument("project_dir", help="Path to project directory")
    args = parser.parse_args()
    project_path = (Path.cwd() / args.project_dir).resolve()
    spec = bind_project(project_path)
    path = write(spec)
    print(path)
