"""Validate that all file paths referenced in a project exist on disk."""

import argparse
import sys
from pathlib import Path

from alidade.render import _abs_source, _load_spec


def _is_file_source(source: str) -> bool:
    """Return True if source is a local path that should already exist.

    Returns False for URIs, memory layers, or derived outputs that
    make prepare would generate.
    """
    if ":" in source.split("/")[0]:  # http-header:, wms:, etc.
        return False
    if source.startswith("memory?"):
        return False
    if source.startswith("./output/"):  # generated by make prepare, not yet present
        return False
    return True


def validate(project_dir: Path) -> bool:
    """Validate that all source and style paths for a project exist on disk."""
    spec = _load_spec(project_dir)
    errors: list[str] = []

    for layer in spec.layers:
        if layer.style_xml is not None:
            xml_path = project_dir / layer.style_xml
            if not xml_path.exists():
                errors.append(f"  [{layer.id}] style_xml not found: {xml_path}")

        if _is_file_source(layer.source):
            abs_path = Path(_abs_source(layer.source, project_dir).split("|")[0])
            if not abs_path.exists():
                errors.append(f"  [{layer.id}] source not found: {abs_path}")

    if errors:
        print(f"validation failed ({project_dir.name}):")
        for e in errors:
            print(e)
        return False

    print(f"ok ({project_dir.name}, {len(spec.layers)} layers)")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate that all source and style paths for a project exist."
    )
    parser.add_argument("project_dir", help="Path to project directory")
    args = parser.parse_args()
    ok = validate((Path.cwd() / args.project_dir).resolve())
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
